version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - c:/Users/Administrator/go/src/vinid_project:/usr/src/app2
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_DATABASE=vinid_project
    volumes:
      - database_mysql:/var/lib/mysql/
    networks:
      - fullstack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=root
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack

volumes:
  database_mysql:                  


                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
