version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure    
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
        - MYSQL_DATABASE=vinid_project
    volumes:
      - database_mysql:/var/lib/mysql/
    networks:
      - fullstack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql
      - PMA_USER=root
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack

volumes:
  database_mysql:          


networks:
  fullstack:
    driver: bridge
